In [1]:
#Group 7 BrenningmeyerHerkenrathMishra

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
def ReactionRates(r,X):
        R = np.zeros((4,1))
        R[0] = r[0]
        R[1] = r[1]*X[0]
        R[2] = r[2]*X[0]*X[2]
        R[3] = r[3]*X[1]
        R[4] = r[4]*X[1]
        R[5] = r[5]*X[2]
        return R[:,0]

In [4]:
t_data, y_data = np.load('Data.npy')

print(t_data) #timepoints
print(y_data) #virus concentration


[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
[  18.77820809   49.7870446   790.47121748 2319.52125822 1672.42748726
 1496.9055885  1153.46416351  850.42392024 1082.9824603   679.71679033
  452.55356816  553.01483385  546.2234647   315.55576672  479.59435354
  476.2916805   479.97009311  488.58366905  486.22514615  582.62533495
  343.3053144 ]


In [8]:
# Stoichiometric matrix
s = np.array([[1,0,0],[-1,0,0],[-1,1,-1],[0,-1,0],[0,0,1],[0,0,-1]])

# Reaction parameters
k0 = 100
k1 = 0.1
c2 =1 #change to unknown parameters
c3 =1 #change to unknown parameters
c4 =1 #change to unknown parameters
c5 =1 #change to unknown parameters

#initial
X0 = [k0/k1, 0, 20]

#list of parameters 
r = [k0, k1*X0[1], c2*X0[0]*X0[2], c3*X0[1], c4*X0[1], c5*X0[2]]

In [7]:
print(s)

[[ 1  0  0]
 [-1  0  0]
 [-1  1 -1]
 [ 0 -1  0]
 [ 0  0  1]
 [ 0  0 -1]]
